"""
Django settings for MyDjango project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

#abspath表示上一级目录
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#密钥,方便后期加密时使用
SECRET_KEY = 'ysecz1aih+n#ez=5w573+ba519ek4sytsgta2nwg#0bhijvc(0'

# SECURITY WARNING: don't run with debug turned on in production!
#Django默认开启调试模式，True；如果不在调试环境，Django不再提供静态文件访问支持
DEBUG = True

#允许哪些域名访问Django服务器
ALLOWED_HOSTS = []


# Application definition

#安装或注册应用
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #如果应用中定义的模型，并要做迁移建表时，必须注册/安装应用，如果应用中只有路由和视图这些代码应用可注册可不注册
    'sixi.apps.SixiConfig', #安装
    #富文本编辑器
    'ckeditor',
    'ckeditor_uploader',

    #多级评论
    'django.contrib.sites',
    'django_comments',
    'django_mptt_comments',
    'captcha',
    'mptt',
    'comment.apps.CommentConfig',
]

MPTT_COMMENTS_ALLOW_ANONYMOUS = True # True 为允许匿名评论，否则不允许
COMMENTS_APP = 'django_mptt_comments'
SITE_ID = 1

#中间件：监听请求和响应中间过程
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #禁用CSRF认证，不然无法进行POST,PUT,DELETE 请求
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #自定义中间件
    # 'sixi.middleware.my_middleware',
    # 'sixi.middleware.my_middleware2',


    #多级评论
    'crequest.middleware.CrequestMiddleware',
]

#工程路由入口文件：总路由
ROOT_URLCONF = 'MyDjango.urls'

#工程模板配置项
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #模板加载存放目录
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#项目上线后的文件启动入口
WSGI_APPLICATION = 'MyDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#项目数据库配置项
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 数据库驱动
        'NAME': 'cht',  # 数据库名
        'USER': 'root',  # 用户名
        'PASSWORD': 't0115.fendou',  # 密码，本机mysql数据库没有设置密码，故此处为空，此处应修改为自己的数据库密码
        'HOST': '127.0.0.1',  # 主机ip
        'PORT': '3306'  # 数据库端口号
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

#密码认证配置项
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

#本地化
LANGUAGE_CODE = 'zh-hans'

#时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

#静态文件访问路径前缀
STATIC_URL = '/static/'

#指定静态文件存储/加载目录

STATICFILES_DIRS = [(os.path.join(BASE_DIR, 'static'))]

#后台创建文件
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
CKEDITOR_UPLOAD_PATH = 'upload/'

#修改Django的缓存，由默认的内存缓存cache改成 redis缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

#让session 使用缓存
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
#让session缓存到redis的几号数据库
SESSION_CACHE_ALIAS = "default"


#多级评论
MPTT_COMMENTS_ALLOW_ANONYMOUS = True # True 为允许匿名评论，否则不允许