# Generated by Django 3.1.2 on 2020-12-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixi', '0004_auto_20201222_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
